import { DefaultMetricSpec } from "@/lib/types";

export const DEFAULT_METRICS: DefaultMetricSpec[] = [
  {
    key: "cmj",
    label: "CMJ",
    unit: "cm",
    higherIsBetter: true,
    benchRecreational: 30,
    benchTrained: 42,
    benchElite: 60,
  },
  {
    key: "sj",
    label: "SJ",
    unit: "cm",
    higherIsBetter: true,
    benchRecreational: 25,
    benchTrained: 38,
    benchElite: 55,
  },
  {
    key: "abalakov",
    label: "Abalakov",
    unit: "cm",
    higherIsBetter: true,
    benchRecreational: 34,
    benchTrained: 47,
    benchElite: 65,
  },
  {
    key: "rsi",
    label: "RSI",
    unit: "",
    higherIsBetter: true,
    benchRecreational: 0.8,
    benchTrained: 1.5,
    benchElite: 2.5,
  },
  {
    key: "tempoContato",
    label: "Tempo de Contato",
    unit: "ms",
    higherIsBetter: false,
    benchRecreational: 300,
    benchTrained: 230,
    benchElite: 170,
  },
  {
    key: "alturaSaltoDJ",
    label: "Altura Salto DJ",
    unit: "cm",
    higherIsBetter: true,
    benchRecreational: 25,
    benchTrained: 35,
    benchElite: 48,
  },
  {
    key: "cmjEsquerdo",
    label: "CMJ Esquerdo",
    unit: "cm",
    higherIsBetter: true,
    benchRecreational: 28,
    benchTrained: 40,
    benchElite: 58,
  },
  {
    key: "cmjDireito",
    label: "CMJ Direito",
    unit: "cm",
    higherIsBetter: true,
    benchRecreational: 28,
    benchTrained: 40,
    benchElite: 58,
  },
  {
    key: "assimetriaPercentual",
    label: "Assimetria %",
    unit: "%",
    higherIsBetter: false,
    benchRecreational: 12,
    benchTrained: 7,
    benchElite: 3,
  },
  {
    key: "saltoHorizontal",
    label: "Salto Horizontal",
    unit: "cm",
    higherIsBetter: true,
    benchRecreational: 175,
    benchTrained: 230,
    benchElite: 285,
  },
];

export const DEFAULT_METRIC_MAP: Record<string, DefaultMetricSpec> =
  Object.fromEntries(DEFAULT_METRICS.map((m) => [m.key, m]));
